# -*- coding: utf-8 -*-
"""src/data_analyzer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PP0iS3h5tVidZUF_FpUk5mbPNZxTibdH
"""

"""
data_analyzer.py
Module phân tích đặc tính dữ liệu cho Adaptive Sort.
"""

def count_inversions(arr):
    """
    Đếm số lượng nghịch thế trong mảng bằng merge sort cải tiến.

    Args:
        arr (list): Danh sách các số (int/float).

    Returns:
        int: Số cặp (i, j) với i < j và arr[i] > arr[j].

    Complexity: O(n log n)
    """
    def merge_count_split_inv(sub_arr):
        if len(sub_arr) <= 1:
            return sub_arr, 0
        mid = len(sub_arr) // 2
        left, inv_left = merge_count_split_inv(sub_arr[:mid])
        right, inv_right = merge_count_split_inv(sub_arr[mid:])

        merged = []
        i = j = 0
        inv = inv_left + inv_right

        while i < len(left) and j < len(right):
            if left[i] <= right[j]:
                merged.append(left[i])
                i += 1
            else:
                merged.append(right[j])
                # Mọi phần tử còn lại trong left đều > right[j]
                inv += len(left) - i
                j += 1

        merged.extend(left[i:])
        merged.extend(right[j:])
        return merged, inv

    _, inv_count = merge_count_split_inv(arr.copy())
    return inv_count

def inversion_ratio(arr):
    """
    Tính tỷ lệ nghịch thế = (số nghịch thế / tổng số cặp) * 100%.

    Args:
        arr (list): Danh sách số.

    Returns:
        float: Tỷ lệ phần trăm (0-100).
    """
    n = len(arr)
    if n < 2:
        return 0.0
    max_inv = n * (n - 1) / 2
    inv = count_inversions(arr)
    return (inv / max_inv) * 100

def detect_trend(arr):
    """
    Phát hiện xu hướng chính của dữ liệu dựa trên so sánh lân cận.

    Args:
        arr (list): Danh sách số.

    Returns:
        str: 'increasing' (tăng dần), 'decreasing' (giảm dần), 'random' (ngẫu nhiên).

    Complexity: O(n)
    """
    n = len(arr)
    if n < 3:
        return 'random'

    inc = dec = 0
    for i in range(1, n):
        if arr[i] > arr[i-1]:
            inc += 1
        elif arr[i] < arr[i-1]:
            dec += 1

    total = inc + dec
    if total == 0:
        return 'random'

    ratio_inc = inc / total
    ratio_dec = dec / total

    if ratio_inc > 0.8:
        return 'increasing'
    elif ratio_dec > 0.8:
        return 'decreasing'
    else:
        return 'random'

# ========== PHẦN KIỂM THỬ NHANH (chạy khi file được thực thi trực tiếp) ==========
if __name__ == "__main__":
    # Test 1: mảng tăng dần
    arr1 = [1, 2, 3, 4, 5]
    print("arr1 (tăng):", arr1)
    print("  inversion_ratio =", inversion_ratio(arr1))   # 0.0
    print("  trend =", detect_trend(arr1))                # increasing

    # Test 2: mảng giảm dần
    arr2 = [5, 4, 3, 2, 1]
    print("\narr2 (giảm):", arr2)
    print("  inversion_ratio =", inversion_ratio(arr2))   # 100.0
    print("  trend =", detect_trend(arr2))                # decreasing

    # Test 3: mảng ngẫu nhiên nhỏ
    import random
    random.seed(42)
    arr3 = random.sample(range(100), 20)
    print("\narr3 (ngẫu nhiên 20 phần tử):")
    print("  inversion_ratio =", inversion_ratio(arr3))
    print("  trend =", detect_trend(arr3))