# -*- coding: utf-8 -*-
"""src/adaptive_sort.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PP0iS3h5tVidZUF_FpUk5mbPNZxTibdH
"""

# -*- coding: utf-8 -*-
"""
sort_algorithms.py
Các thuật toán sắp xếp thuần túy (Insertion, Quick, Merge, Heap) và hàm kiểm tra.
Viết bởi Trần Thị Thu Hường.
Đã điều chỉnh để phù hợp với quy tắc chung của nhóm.
"""

# =====================================
# 1. Insertion Sort
# =====================================
def insertion_sort(arr):
    """Sắp xếp chèn tại chỗ, trả về chính list đó."""
    for i in range(1, len(arr)):
        key = arr[i]
        j = i - 1
        while j >= 0 and arr[j] > key:
            arr[j + 1] = arr[j]
            j -= 1
        arr[j + 1] = key
    return arr


# =====================================
# 2. Quick Sort (median-of-three)
# =====================================
def _median_of_three(arr, left, right):
    mid = (left + right) // 2
    if arr[left] > arr[mid]:
        arr[left], arr[mid] = arr[mid], arr[left]
    if arr[left] > arr[right]:
        arr[left], arr[right] = arr[right], arr[left]
    if arr[mid] > arr[right]:
        arr[mid], arr[right] = arr[right], arr[mid]
    arr[mid], arr[right - 1] = arr[right - 1], arr[mid]
    return arr[right - 1]

def _quick_sort_recursive(arr, left, right):
    if left >= right:
        return
    # Tối ưu đoạn nhỏ (<=10 phần tử) dùng insertion sort
    if right - left + 1 <= 10:
        for i in range(left + 1, right + 1):
            key = arr[i]
            j = i - 1
            while j >= left and arr[j] > key:
                arr[j + 1] = arr[j]
                j -= 1
            arr[j + 1] = key
        return
    pivot = _median_of_three(arr, left, right)
    i = left
    j = right - 1
    while True:
        i += 1
        while arr[i] < pivot:
            i += 1
        j -= 1
        while arr[j] > pivot:
            j -= 1
        if i < j:
            arr[i], arr[j] = arr[j], arr[i]
        else:
            break
    arr[i], arr[right - 1] = arr[right - 1], arr[i]
    _quick_sort_recursive(arr, left, i - 1)
    _quick_sort_recursive(arr, i + 1, right)

def quick_sort(arr):
    """Wrapper cho Quick Sort, sắp xếp tại chỗ, trả về list."""
    if len(arr) <= 1:
        return arr
    _quick_sort_recursive(arr, 0, len(arr) - 1)
    return arr


# =====================================
# 3. Merge Sort
# =====================================
def _merge(arr, left, mid, right):
    temp = []
    i, j = left, mid + 1
    while i <= mid and j <= right:
        if arr[i] <= arr[j]:
            temp.append(arr[i])
            i += 1
        else:
            temp.append(arr[j])
            j += 1
    while i <= mid:
        temp.append(arr[i])
        i += 1
    while j <= right:
        temp.append(arr[j])
        j += 1
    for k in range(len(temp)):
        arr[left + k] = temp[k]

def _merge_sort_recursive(arr, left, right):
    if left >= right:
        return
    mid = (left + right) // 2
    _merge_sort_recursive(arr, left, mid)
    _merge_sort_recursive(arr, mid + 1, right)
    _merge(arr, left, mid, right)

def merge_sort(arr):
    """Wrapper cho Merge Sort, sắp xếp tại chỗ, trả về list."""
    if len(arr) <= 1:
        return arr
    _merge_sort_recursive(arr, 0, len(arr) - 1)
    return arr


# =====================================
# 4. Heap Sort
# =====================================
def _heapify(arr, n, i):
    largest = i
    left = 2 * i + 1
    right = 2 * i + 2
    if left < n and arr[left] > arr[largest]:
        largest = left
    if right < n and arr[right] > arr[largest]:
        largest = right
    if largest != i:
        arr[i], arr[largest] = arr[largest], arr[i]
        _heapify(arr, n, largest)

def heap_sort(arr):
    """Heap Sort tại chỗ, trả về list."""
    n = len(arr)
    for i in range(n // 2 - 1, -1, -1):
        _heapify(arr, n, i)
    for i in range(n - 1, 0, -1):
        arr[0], arr[i] = arr[i], arr[0]
        _heapify(arr, i, 0)
    return arr


# =====================================
# 5. Hàm kiểm tra đã sắp xếp
# =====================================
def is_sorted(arr):
    """Kiểm tra mảng có tăng dần không."""
    for i in range(len(arr) - 1):
        if arr[i] > arr[i + 1]:
            return False
    return True


# =====================================
# 6. Test thử (chạy khi file được thực thi trực tiếp)
# =====================================
if __name__ == "__main__":
    test_arr = [8, 3, 5, 2, 9, 1, 4, 7, 6]
    print("Mảng ban đầu:", test_arr)

    a1 = test_arr.copy()
    insertion_sort(a1)
    print("Insertion:", a1, "| Sorted:", is_sorted(a1))

    a2 = test_arr.copy()
    quick_sort(a2)
    print("Quick:", a2, "| Sorted:", is_sorted(a2))

    a3 = test_arr.copy()
    merge_sort(a3)
    print("Merge:", a3, "| Sorted:", is_sorted(a3))

    a4 = test_arr.copy()
    heap_sort(a4)
    print("Heap:", a4, "| Sorted:", is_sorted(a4))