# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dwuRUAa4k0_FfOXJ_CC-1q2zP22eo3Wh
"""

# =====================================
# 1. Insertion Sort
# =====================================
def insertion_sort(a):
    for i in range(1, len(a)):
        key = a[i]
        j = i - 1

        while j >= 0 and a[j] > key:
            a[j + 1] = a[j]
            j -= 1

        a[j + 1] = key


# =====================================
# 2. Quick Sort (median-of-three)
# =====================================
def median_of_three(a, left, right):
    mid = (left + right) // 2

    if a[left] > a[mid]:
        a[left], a[mid] = a[mid], a[left]
    if a[left] > a[right]:
        a[left], a[right] = a[right], a[left]
    if a[mid] > a[right]:
        a[mid], a[right] = a[right], a[mid]

    # đưa pivot về vị trí right-1
    a[mid], a[right - 1] = a[right - 1], a[mid]
    return a[right - 1]


def quick_sort(a, left, right):
    if left >= right:
        return

    # tối ưu đoạn nhỏ (<=10 phần tử)
    if right - left + 1 <= 10:
        for i in range(left + 1, right + 1):
            key = a[i]
            j = i - 1
            while j >= left and a[j] > key:
                a[j + 1] = a[j]
                j -= 1
            a[j + 1] = key
        return

    pivot = median_of_three(a, left, right)

    i = left
    j = right - 1

    while True:
        i += 1
        while a[i] < pivot:
            i += 1

        j -= 1
        while a[j] > pivot:
            j -= 1

        if i < j:
            a[i], a[j] = a[j], a[i]
        else:
            break

    # đưa pivot về đúng vị trí
    a[i], a[right - 1] = a[right - 1], a[i]

    quick_sort(a, left, i - 1)
    quick_sort(a, i + 1, right)


# =====================================
# 3. Merge Sort
# =====================================
def merge(a, left, mid, right):
    temp = []
    i = left
    j = mid + 1

    while i <= mid and j <= right:
        if a[i] <= a[j]:
            temp.append(a[i])
            i += 1
        else:
            temp.append(a[j])
            j += 1

    while i <= mid:
        temp.append(a[i])
        i += 1

    while j <= right:
        temp.append(a[j])
        j += 1

    for k in range(len(temp)):
        a[left + k] = temp[k]


def merge_sort(a, left, right):
    if left >= right:
        return

    mid = (left + right) // 2
    merge_sort(a, left, mid)
    merge_sort(a, mid + 1, right)
    merge(a, left, mid, right)


# =====================================
# 4. Heap Sort
# =====================================
def heapify(a, n, i):
    largest = i
    left = 2 * i + 1
    right = 2 * i + 2

    if left < n and a[left] > a[largest]:
        largest = left

    if right < n and a[right] > a[largest]:
        largest = right

    if largest != i:
        a[i], a[largest] = a[largest], a[i]
        heapify(a, n, largest)


def heap_sort(a):
    n = len(a)

    # build heap
    for i in range(n // 2 - 1, -1, -1):
        heapify(a, n, i)

    # extract
    for i in range(n - 1, 0, -1):
        a[0], a[i] = a[i], a[0]
        heapify(a, i, 0)


# =====================================
# 5. Hàm kiểm tra is_sorted
# =====================================
def is_sorted(a):
    for i in range(len(a) - 1):
        if a[i] > a[i + 1]:
            return False
    return True


# =====================================
# 6. Test thử
# =====================================
if __name__ == "__main__":
    arr = [8, 3, 5, 2, 9, 1, 4, 7, 6]

    print("Mảng ban đầu:", arr)

    # Insertion
    a1 = arr.copy()
    insertion_sort(a1)
    print("Insertion:", a1, "| Sorted:", is_sorted(a1))

    # Quick
    a2 = arr.copy()
    quick_sort(a2, 0, len(a2) - 1)
    print("Quick:", a2, "| Sorted:", is_sorted(a2))

    # Merge
    a3 = arr.copy()
    merge_sort(a3, 0, len(a3) - 1)
    print("Merge:", a3, "| Sorted:", is_sorted(a3))

    # Heap
    a4 = arr.copy()
    heap_sort(a4)
    print("Heap:", a4, "| Sorted:", is_sorted(a4))